services:
  - type: web
    name: goldlens-core
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8081
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOLDPRICEZ_API_KEY
        sync: false
      - key: GOLD_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
    healthCheckPath: /actuator/health
